<?php
use com\extremeidea\bidorbuy\storeintegrator\core as bobsi;
$warnings = array_merge(
    bobsi\StaticHolder::getBidorbuyStoreIntegrator()->getWarnings(),
    bobsi\StaticHolder::getWarnings()->getBusinessWarnings()
);

foreach ($warnings as $warning) {
    echo "
        <div id='messages'>
            <ul class='messages'>
                <li class='error-msg'>
                    <ul>
                        <li>
                            <span>$warning</span>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        ";
}
?>

<div id="bobsi-icon-trade-feed"></div>
<div id="bobsi-adv">
    <!-- BEGIN ADVERTPRO CODE BLOCK -->
    <script type="text/javascript">
        document.write('<scr' + 'ipt src="http://nope.bidorbuy.co.za/servlet/view/banner/javascript/zone?zid=153&pid=0&random=' + Math.floor(89999999 * Math.random() + 10000000) + '&millis=' + new Date().getTime() + '&referrer=' + encodeURIComponent(document.location) + '" type="text/javascript"></scr' + 'ipt>');
    </script>
    <!-- END ADVERTPRO CODE BLOCK -->
</div>